/** @param {NS} ns */
//
// Scans every rooted server the player has access to, finds any
// Coding Contract (.cct) files lying around, solves them, and
// submits the answers via the coding contract API. Each contract
// has a fixed number of attempts (typically 10); once a contract
// is failed, it's GONE (along with the reputation/money reward).
// That makes "scan + solve + submit" a one-shot high-stakes loop:
// there's no "I'll try again later" — by the time you re-run the
// script, the file may have been deleted from a failed attempt.
//
// Why a separate file (and not "slap it onto monitor-X.js"):
//   The contract rewards are sizable (reputation toward factions,
//   rare augs, money) but each contract is a one-shot. A long-
//   lived monitor that just "scans every X minutes" is the wrong
//   shape: contracts spawn when you hack servers, and the spawn
//   cadence is decoupled from the script's poll interval. The
//   natural unit is "scan once, solve everything, exit". A
//   long-lived mode is provided for the corner case where the
//   player wants to leave it running (e.g. overnight) — the loop
//   re-scans on a configurable interval and silently does nothing
//   when there's nothing to do.
//
// What you get out of it:
//   - Money: contracts pay out (small, but real).
//   - Faction reputation: solving contracts gives rep with the
//     faction that owns the server (or, in some cases, random
//     factions). This is the real reward — high-tier augs are
//     gated on faction rep.
//   - Rare augs: some contracts drop specific augmentations.
//
//   → Set --once to do a single pass and exit (the recommended
//     mode; you only need to run it after hacking a new server
//     that has a contract on it).
//   → Use the loop mode for AFK overnight grinding.
//
// Solvers:
//   The 29 contract types are all implemented in `lib/cct-solvers.js`.
//   This script is the scanner/loop; the math lives in the lib.
//   If a new contract type is added to the game, drop a new
//   entry in SOLVERS and the scanner picks it up — no edits
//   here.
//
// Failure modes:
//   1. Unknown contract type (new in a future update). The
//      scanner reports it and skips. Update lib/cct-solvers.js
//      to add it.
//   2. Solver throws (bad input, edge case). The scanner
//      reports the error message and SKIPS — does NOT submit.
//      This is intentional: a wrong submission burns an
//      attempt, and we want to preserve attempts for cases
//      we're confident about. If the solver is wrong, the
//      user can submit manually via the in-game UI.
//   3. ns.codingcontract.attempt() returns "" — the answer
//      was wrong. We log "FAIL-solve" and move on. The
//      contract file remains, with attempts decremented.
//
// Scope:
//   We only process contracts on servers the player has root
//   on. "Rooted" = ns.hasRootAccess(host) === true. This
//   covers all servers the player can currently interact
//   with, including purchased servers and home.
//
//   We also include home, which sometimes has contracts
//   generated by external events (e.g. faction invites, the
//   "Generate Coding Contract" Singularity function).
//
//   We skip servers that are not rooted, including other
//   players' hacknet servers and unrooted world servers.
//
// Output is QUIET by default — only SOLVED / FAIL / UNKNOWN
// contract type / summary lines print. --verbose re-enables
// per-contract SCAN lines. --once runs a single pass with
// full output.
//
// Usage:
//   run monitor-cct.js                      # one scan, exit (default)
//   run monitor-cct.js --once               # same, explicit
//   run monitor-cct.js --loop               # scan every 60s, indefinitely
//   run monitor-cct.js --loop --interval 30 # every 30s
//   run monitor-cct.js --verbose            # show every scanned file
//   run monitor-cct.js --dry-run            # find contracts but don't submit
//
const USAGE = `Usage:
 run monitor-cct.js                      # one scan, exit
 run monitor-cct.js --once               # same, explicit
 run monitor-cct.js --loop               # scan every 60s, indefinitely
 run monitor-cct.js --loop --interval 30 # every 30s
 run monitor-cct.js --verbose            # show every scanned file
 run monitor-cct.js --dry-run            # find contracts but don't submit
`;

import { SOLVERS } from "/lib/cct-solvers.js";

const DEFAULT_INTERVAL_MS = 60_000;

export async function main(ns) {
  if (ns.args.includes("-h") || ns.args.includes("--help")) {
    ns.tprint(USAGE);
    return;
  }

  // Parse args. The naming is slightly idiosyncratic: --once
  // is the DEFAULT behavior, but we accept --loop to opt into
  // indefinite rescan. We also accept --interval to control
  // the rescan cadence in loop mode. --dry-run reads the
  // contracts but doesn't submit — useful for verifying the
  // solver set covers all the contracts on your servers.
  const args = ns.args.slice();
  const once = args.includes("--once") || !args.includes("--loop");
  const verbose = args.includes("--verbose");
  const dryRun = args.includes("--dry-run");
  const intervalIdx = args.indexOf("--interval");
  const intervalMs = intervalIdx >= 0 ? Number(args[intervalIdx + 1]) : DEFAULT_INTERVAL_MS;
  if (intervalIdx >= 0 && (!Number.isFinite(intervalMs) || intervalMs < 0)) {
    ns.tprint(`monitor-cct: --interval must be a non-negative number (got ${args[intervalIdx + 1]})`);
    return;
  }

  ns.disableLog("sleep");
  ns.disableLog("scan");
  ns.disableLog("ls");
  ns.disableLog("getServerMoneyAvailable");
  ns.disableLog("codingcontract.attempt");
  ns.disableLog("codingcontract.getContractType");
  ns.disableLog("codingcontract.getData");

  // Build the list of rooted servers. We do a BFS from home
  // via ns.scan(), which returns the network graph. A server
  // is in scope iff ns.hasRootAccess(host) === true. We also
  // include home explicitly (ns.scan from home returns the
  // list of neighbors, not home itself).
  //
  // Dedup is handled by the `seen` set — without it, a graph
  // cycle (e.g. CSEC ↔ joesguns) would loop forever.
  function listRootedServers() {
    const out = ["home"];  // home always counts
    const seen = new Set(["home"]);
    const queue = ["home"];
    while (queue.length > 0) {
      const cur = queue.shift();
      const neighbors = ns.scan(cur);
      for (const n of neighbors) {
        if (seen.has(n)) continue;
        seen.add(n);
        if (!ns.hasRootAccess(n)) continue;  // skip unrooted
        out.push(n);
        queue.push(n);
      }
    }
    return out;
  }

  // One scan pass. Returns the counters object. Each tick:
  //   1. Build the rooted-servers list.
  //   2. For each server, list .cct files.
  //   3. For each contract: read type, read data, look up solver,
  //      submit (unless --dry-run), and log the result.
  //
  // The order in which we process contracts is "every .cct on
  // server A, then every .cct on server B, ...". There's no
  // priority between contracts; reputation rewards are
  // independent of order.
  function pass() {
    const counters = { solved: 0, failed: 0, skipped: 0, unknown: 0, errored: 0 };
    const servers = listRootedServers();
    for (const host of servers) {
      let files;
      try {
        // ns.ls(host, ".cct") returns all filenames on the
        // server ending in .cct. The substring filter is
        // case-sensitive; .cct is always lowercase in the
        // game.
        files = ns.ls(host, ".cct");
      } catch (e) {
        // ns.ls can throw on a server we lost access to
        // mid-script (e.g. we just sold a purchased server).
        // Skip and move on.
        if (verbose) ns.tprint(`SKIP-ls         ${host}: ${e}`);
        continue;
      }
      for (const filename of files) {
        let type, data, tries;
        try {
          type = ns.codingcontract.getContractType(filename, host);
          data = ns.codingcontract.getData(filename, host);
          tries = ns.codingcontract.getNumTriesRemaining(filename, host);
        } catch (e) {
          // Contract might have been removed by another script
          // (a parallel run of this very script, or a
          // failure-driven delete). Skip.
          counters.skipped++;
          if (verbose) ns.tprint(`SKIP-read       ${host}/${filename}: ${e}`);
          continue;
        }
        if (verbose) {
          ns.tprint(`SCAN            ${host}/${filename}  type="${type}"  tries=${tries}`);
        }
        const solver = SOLVERS[type];
        if (!solver) {
          // New / unsupported type. Print loudly so the user
          // notices and updates lib/cct-solvers.js. We do NOT
          // submit anything (there's nothing to submit).
          counters.unknown++;
          ns.tprint(`UNKNOWN         ${host}/${filename}  type="${type}" — add a solver to lib/cct-solvers.js`);
          continue;
        }
        let answer;
        try {
          answer = solver(data);
        } catch (e) {
          // Solver threw. We surface the message and skip.
          // Crucially, we do NOT call attempt() with a bad
          // answer — that would burn an attempt.
          counters.errored++;
          const msg = typeof e === "string" ? e : (e && e.message) || String(e);
          ns.tprint(`ERROR-solver    ${host}/${filename}  type="${type}": ${msg}`);
          continue;
        }
        if (dryRun) {
          counters.solved++;
          ns.tprint(`DRY             ${host}/${filename}  type="${type}"  answer=${JSON.stringify(answer)}`);
          continue;
        }
        // Submit. attempt() returns a non-empty string on
        // success ("<reward description>") and "" on failure.
        // The return value is informational; we don't need to
        // parse it.
        const result = ns.codingcontract.attempt(answer, filename, host);
        if (result) {
          counters.solved++;
          ns.tprint(`SOLVED          ${host}/${filename}  type="${type}"  → ${result}`);
        } else {
          counters.failed++;
          ns.tprint(`FAIL-solve      ${host}/${filename}  type="${type}"  answer=${JSON.stringify(answer)}`);
        }
      }
    }
    return counters;
  }

  if (once) {
    // One pass. Print a short summary at the end regardless of
    // the per-contract quiet setting — the user explicitly
    // wanted to scan, so they want to know if anything
    // happened.
    const c = pass();
    const summary = `done: solved=${c.solved} failed=${c.failed} errored=${c.errored} unknown=${c.unknown} skipped=${c.skipped}`;
    if (c.solved + c.failed + c.errored + c.unknown > 0 || verbose) {
      ns.tprint(summary);
    } else {
      ns.tprint("monitor-cct: no contracts found");
    }
    return;
  }

  ns.tprint(`monitor-cct: loop mode, interval=${intervalMs}ms, output=${verbose ? "verbose" : "quiet"}`);
  while (true) {
    const c = pass();
    if (c.solved + c.failed + c.errored + c.unknown > 0) {
      ns.tprint(`tick: solved=${c.solved} failed=${c.failed} errored=${c.errored} unknown=${c.unknown}`);
    }
    await ns.sleep(intervalMs);
  }
}
